'use client';

import React, { useState, useEffect } from 'react';
import { BookMarked, Sparkles, RefreshCw, CheckSquare, Square, Download, FileText } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Paper, LiteratureReview } from '@/lib/types';
import { api } from '@/lib/api';

interface LiteratureReviewModalProps {
  workspaceId: string;
  papers: Paper[];
}

export const LiteratureReviewModal: React.FC<LiteratureReviewModalProps> = ({ workspaceId, papers }) => {
  const [selectedIds, setSelectedIds] = useState<string[]>(papers.map(p => p.id));
  const [topic, setTopic] = useState('');
  const [loading, setLoading] = useState(false);
  const [review, setReview] = useState<LiteratureReview | null>(null);

  useEffect(() => {
    setSelectedIds(papers.map(p => p.id));
  }, [papers]);

  const toggleSelectPaper = (id: string) => {
    setSelectedIds(prev =>
      prev.includes(id) ? prev.filter(item => item !== id) : [...prev, id]
    );
  };

  const handleGenerateReview = async () => {
    if (selectedIds.length === 0) return;
    setLoading(true);
    try {
      const res = await api.createLiteratureReview(workspaceId, selectedIds, topic);
      setReview(res);
    } catch (err: any) {
      alert(`Error generating literature review: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleExportPdf = () => {
    if (!review) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    const reviewContentHtml = document.querySelector('.review-markdown-body')?.innerHTML || '';

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${review.title}</title>
          <style>
            body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; color: #2D372E; line-height: 1.7; background: #ffffff; }
            h1 { color: #1E251E; font-size: 24px; border-bottom: 2px solid #8FA28A; padding-bottom: 10px; margin-bottom: 8px; }
            .meta { font-size: 11px; color: #7A877B; margin-bottom: 30px; }
            h2 { color: #3D4A39; font-size: 17px; margin-top: 24px; border-bottom: 1px solid #E2DED4; padding-bottom: 6px; }
            h3 { color: #54664F; font-size: 14px; margin-top: 18px; }
            p { font-size: 13px; color: #4A554C; margin-bottom: 12px; }
            ul, ol { font-size: 13px; color: #4A554C; padding-left: 20px; }
            li { margin-bottom: 6px; }
            code { background: #F7F4ED; padding: 2px 6px; border-radius: 4px; font-size: 12px; font-family: monospace; }
            blockquote { border-left: 3px solid #C8A96B; margin: 0; padding-left: 14px; color: #6E5528; background: #FBF7EE; font-style: italic; }
            @media print {
              body { padding: 20px; }
            }
          </style>
        </head>
        <body>
          <h1>${review.title}</h1>
          <div class="meta">Generated by LitLens AI Research Assistant • ${review.cited_paper_ids.length} Papers Cited</div>
          <div class="content">${reviewContentHtml}</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 400);
  };

  return (
    <div className="p-6 space-y-6 max-w-6xl mx-auto">
      {/* Header */}
      <div className="bg-white p-6 rounded-2xl border border-[#E2DED4] shadow-xs space-y-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <BookMarked className="w-5 h-5 text-[#8FA28A]" />
            <h2 className="text-xl font-bold text-[#2D372E]">Thematic Literature Review Copilot</h2>
          </div>
          <p className="text-xs text-[#7A877B]">
            Synthesize selected papers into a structured, thematic literature review with inline paper citations.
          </p>
        </div>

        {/* Inputs */}
        <div className="flex flex-col sm:flex-row items-center gap-3">
          <input
            type="text"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="Review Focus / Topic (e.g. LLM Hallucination & Evidence Grounding)"
            className="flex-1 bg-[#F7F4ED] border border-[#E2DED4] focus:border-[#8FA28A] focus:ring-2 focus:ring-[#8FA28A]/20 rounded-xl px-3.5 py-2 text-xs text-[#2D372E] placeholder-[#7A877B] outline-none w-full"
          />
          <button
            onClick={handleGenerateReview}
            disabled={selectedIds.length === 0 || loading}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-[#C8A96B] hover:bg-[#B59453] disabled:opacity-50 text-white font-medium text-xs shadow-xs transition whitespace-nowrap"
          >
            {loading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
            Generate Review ({selectedIds.length} papers)
          </button>
        </div>

        {/* Paper Selection */}
        <div className="flex flex-wrap items-center gap-2 pt-2 border-t border-[#F7F4ED]">
          <span className="text-xs font-semibold text-[#4A554C] mr-2">Include Papers:</span>
          {papers.map(p => {
            const isSelected = selectedIds.includes(p.id);
            return (
              <button
                key={p.id}
                onClick={() => toggleSelectPaper(p.id)}
                className={`flex items-center gap-2 px-3 py-1.5 rounded-xl text-xs font-medium border transition ${
                  isSelected
                    ? 'bg-[#E8EFE5] text-[#3D4A39] border-[#C7D3C0]'
                    : 'bg-white text-[#4A554C] border-[#E2DED4] hover:border-[#C7D3C0]'
                }`}
              >
                {isSelected ? <CheckSquare className="w-3.5 h-3.5 text-[#8FA28A]" /> : <Square className="w-3.5 h-3.5 text-[#7A877B]" />}
                <span className="truncate max-w-[200px]">{p.title}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Review Reader */}
      {review ? (
        <div className="p-8 bg-white rounded-2xl border border-[#E2DED4] shadow-xs space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#F7F4ED] pb-4">
            <div>
              <h3 className="text-lg font-bold text-[#2D372E]">{review.title}</h3>
              <p className="text-xs text-[#7A877B] mt-1">Generated for workspace papers • {review.cited_paper_ids.length} citations</p>
            </div>
            <button
              onClick={handleExportPdf}
              className="flex items-center justify-center gap-2 px-4 py-2 rounded-xl bg-[#8FA28A] hover:bg-[#54664F] text-white font-semibold text-xs transition shadow-xs"
            >
              <Download className="w-4 h-4" />
              Export to PDF
            </button>
          </div>

          <div className="review-markdown-body prose prose-slate prose-xs max-w-none text-[#4A554C] leading-relaxed space-y-4">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {review.content_markdown}
            </ReactMarkdown>
          </div>
        </div>
      ) : (
        !loading && (
          <div className="text-center py-16 bg-white rounded-2xl border border-[#E2DED4] text-[#7A877B]">
            <BookMarked className="w-12 h-12 mx-auto mb-3 opacity-30 text-[#8FA28A]" />
            <p className="text-sm font-medium text-[#2D372E]">No literature review generated yet</p>
            <p className="text-xs text-[#7A877B] mt-1">Select papers above and click "Generate Review"</p>
          </div>
        )
      )}
    </div>
  );
};
